/**
 ******************************************************************************
 * file    ai_base_product.h
 * author  sunlingge
 * version V100
 * brief   the ai base product.
 ******************************************************************************
 */
#ifndef AI_BASE_PRODUCT_H
#define AI_BASE_PRODUCT_H

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------- Include File -------------------------------------------*/

/*------------------------- Product software name Macro Definition --------------------*/
#define AI_NET_IMAGE_416_416										(0)
#define AI_NET_IMAGE_608_608										(1)
#define AI_PRODUCT_OPTION_NET_IMAGE									(AI_NET_IMAGE_416_416)

/*------------------------- Product board name Macro Definition --------------------*/
//#define AI_PRODUCT_FILE_PATH										"C:/sunlingge/SiAiEm"
//#define AI_PRODUCT_FILE_PATH										"D:/Work/AI/AIWorkspace/SiAiEm"
//#define AI_PRODUCT_LOG_IDENT_PATH									AI_PRODUCT_FILE_PATH"/TestLog/ai/AiIdent/"
//#define AI_PRODUCT_YOLOV3_CONFIG_PATH								"/Source/ai/AiNet/AiNetConfig/AiNetConfigYoloV3/AiNetConfigYoloV3Coco/"
//#define AI_PRODUCT_YOLOV3_TEST_DTA_PATH							"/Source/ai/AiBase/AiBaseIdentData/"
//#define AI_PRODUCT_YOLOV3_TEST_DTA_PATH							"/TestLog/ai/AiIdent/"
//#define AI_PRODUCT_APHPHABET_PATH									AI_PRODUCT_FILE_PATH"/Source/ai/AiBase/AiBaseAlphabetData/"
#define AI_PRODUCT_FILE_PATH										"./"
#define AI_PRODUCT_LOG_IDENT_PATH									AI_PRODUCT_FILE_PATH"/Log/AiIdent/"
#define AI_PRODUCT_YOLOV3_CONFIG_PATH								AI_PRODUCT_FILE_PATH"/Config/AiNetConfigYoloV3/AiNetConfigYoloV3Coco/"
#define AI_PRODUCT_YOLOV3_TEST_DTA_PATH								AI_PRODUCT_LOG_IDENT_PATH
#define AI_PRODUCT_APHPHABET_CONFIG_PATH							AI_PRODUCT_FILE_PATH"/Config/AiBaseAlphabetData/"
#define AI_PRODUCT_APHPHABET_LOG_PATH								AI_PRODUCT_FILE_PATH"/Log/AiBaseAlphabetData/"
#if (AI_PRODUCT_OPTION_NET_IMAGE == AI_NET_IMAGE_416_416)
#define AI_PRODUCT_YOLOV3_CONFIG_FILE								"yolov3_416.cfg"
#endif
#if (AI_PRODUCT_OPTION_NET_IMAGE == AI_NET_IMAGE_608_608)
#define AI_PRODUCT_YOLOV3_CONFIG_FILE								"yolov3_608.cfg"
#endif
#define AI_PRODUCT_YOLOV3_CLASSES_FILE								"coco.data"
#define AI_PRODUCT_YOLOV3_WEIGHTS_FILE								"yolov3.weights"
#define AI_PRODUCT_YOLOV3_WEIGHTS_FILE_FP16							"yolov3.f16.weights"
#define AI_PRODUCT_YOLOV3_1080P_PNG_FILE_FP16						"Layer01080pPng.f16.dat"
#define AI_PRODUCT_YOLOV3_NET_PNG_FILE_FP16							"Layer0NetPng.f16.dat"
#define AI_PRODUCT_YOLOV3_NET_LAYER_FILE							"Output.dat"
#define AI_PRODUCT_YOLOV3_NET_LAYER_FILE_FP16						"Output.f16.dat"
#define AI_PRODUCT_YOLOV3_NET_LAYER_FILE_CMODEL1					"OutputCmodel1.dat"
#define AI_PRODUCT_YOLOV3_NET_LAYER_FILE_CMODEL1_FP16				"OutputCmodel1.f16.dat"
#define AI_PRODUCT_YOLOV3_NET_LAYER_FILE_CMODEL2					"OutputCmodel2.dat"
#define AI_PRODUCT_YOLOV3_NET_LAYER_FILE_CMODEL2_FP16				"OutputCmodel2.f16.dat"
#define AI_PRODUCT_CMODEL_COMMAND_FILE								"CmodelCommand.txt"
#define AI_PRODUCT_CMODEL_CLOCK_FILE								"CmodelClock.txt"
#define AI_PRODUCT_CMODEL_FORWARD_FILE								"CmodelForward.txt"

/*------------------------- Product board name Macro Definition --------------------*/
#define AI_PRODUCT_BOARD_NAME_X86									(1)
#define AI_PRODUCT_BOARD_NAME_SISCTECH								(2)
#define AI_PRODUCT_BOARD_NAME                          				(AI_PRODUCT_BOARD_NAME_SISCTECH)

/*------------------------- Product software name Macro Definition --------------------*/
#define AI_PRODUCT_SOFT_NAME_BOOT									(1)
#define AI_PRODUCT_SOFT_NAME_MONITOR								(2)
#define AI_PRODUCT_SOFT_NAME_APP									(3)
#define AI_PRODUCT_SOFT_NAME_SERVER									(4)
#define AI_PRODUCT_SOFT_NAME                           				(AI_PRODUCT_SOFT_NAME_SERVER)


/*------------------------- Product Option Macro Definition --------------------*/
#if (AI_PRODUCT_SOFT_NAME == AI_PRODUCT_SOFT_NAME_BOOT)
#define AI_PRODUCT_OPTION_BASE                         				(1)
#define AI_PRODUCT_OPTION_BOOT										(1)
#define AI_PRODUCT_OPTION_MANAGE                       				(0)
#define AI_PRODUCT_OPTION_SERVER                       				(0)
#define AI_PRODUCT_OPTION_WIN32										(0)
#endif
#if (AI_PRODUCT_SOFT_NAME == AI_PRODUCT_SOFT_NAME_MONITOR)
#define AI_PRODUCT_OPTION_BASE                         				(1)
#define AI_PRODUCT_OPTION_BOOT										(0)
#define AI_PRODUCT_OPTION_MANAGE                       				(1)
#define AI_PRODUCT_OPTION_SERVER                       				(0)
#define AI_PRODUCT_OPTION_WIN32										(0)
#endif
#if (AI_PRODUCT_SOFT_NAME == AI_PRODUCT_SOFT_NAME_SERVER)
#define AI_PRODUCT_OPTION_BASE                         				(1)
#define AI_PRODUCT_OPTION_BOOT										(0)
#define AI_PRODUCT_OPTION_MANAGE                       				(1)
#define AI_PRODUCT_OPTION_SERVER                       				(1)
#define AI_PRODUCT_OPTION_WIN32										(1)
#endif

/* gpu and ai chip */
#define AI_PRODUCT_ACCELERATOR_CPU									(0)
#define AI_PRODUCT_ACCELERATOR_FPU									(1)
#define AI_PRODUCT_ACCELERATOR_GPU									(2)
#define AI_PRODUCT_ACCELERATOR_SISCTECH_CMODEL1						(3)
#define AI_PRODUCT_ACCELERATOR_SISCTECH_CMODEL2						(4)
#define AI_PRODUCT_ACCELERATOR_SISCTECH_APU							(5)
#define AI_PRODUCT_OPTION_ACCELERATOR_TYPE							(AI_PRODUCT_ACCELERATOR_CPU)

#define AI_PRODUCT_FLOAT_HARDWARE_FP32								(0)
#define AI_PRODUCT_FLOAT_SOFTWARE_FP16								(1)
#define AI_PRODUCT_FLOAT_SOFTWARE_FP32								(2)
#define AI_PRODUCT_FLOAT_SOFTWARE_FP64								(3)
#define AI_PRODUCT_FLOAT_SOFTWARE_INT8								(4)
#define FLOAT_AI_T_TYPE_SIZE										(AI_PRODUCT_FLOAT_HARDWARE_FP32)
#if (FLOAT_AI_T_TYPE_SIZE == AI_PRODUCT_FLOAT_HARDWARE_FP32)
typedef FLOAT32_T FLOAT_AI_T, *FLOAT_AI_T_PTR;
#endif
#if (FLOAT_AI_T_TYPE_SIZE == AI_PRODUCT_FLOAT_SOFTWARE_FP16)
typedef FLOAT16_T FLOAT_AI_T, *FLOAT_AI_T_PTR;
#endif

#if (AI_PRODUCT_OPTION_ACCELERATOR_TYPE == AI_PRODUCT_ACCELERATOR_CPU)
#endif

#if (AI_PRODUCT_OPTION_ACCELERATOR_TYPE == AI_PRODUCT_ACCELERATOR_SISCTECH_CMODEL1)
#define AI_PRODUCT_CMODEL1_GEMM_TYPE_CPU							(0)
#define AI_RRODUCT_CMODEL1_GEMM_TYPE_CMODEL1						(1)
#define AI_PRODUCT_OPTION_CMODEL1_GEMM_TYPE							(AI_RRODUCT_CMODEL1_GEMM_TYPE_CMODEL1)
#endif

#if (AI_PRODUCT_OPTION_ACCELERATOR_TYPE == AI_PRODUCT_ACCELERATOR_SISCTECH_CMODEL2)
#define AI_PRODUCT_CMODEL2_GEMM_TYPE_CPU							(0)
#define AI_RRODUCT_CMODEL2_GEMM_TYPE_CMODEL1						(1)
#define AI_PRODUCT_OPTION_CMODEL2_GEMM_TYPE							(AI_RRODUCT_CMODEL2_GEMM_TYPE_CMODEL1)
#define AI_PRODUCT_CMODEL2_DEBUG_STEP								(0)
#endif

#define AI_PRODUCT_OPTION_LOG										(1)
#define AI_PRODUCT_OPTION_LOG_ALPHABET								(1)
#define AI_PRODUCT_OPTION_LOG_1080P									(1)
#define AI_RPODUCT_OPTION_LOG_FP16									(1)
#define AI_PRODUCT_OPTION_FP16_TEST									(0)
#define AI_PRODUCT_OPTION_FP16_TEST_PRELOAD							(1)
#define AI_PRODUCT_OPTION_FP32_TEST_PRELOAD							(1)
#define AI_PRODUCT_OPTION_WEIGHTS_ADJUST							(0)
#define AI_PRODUCT_OPTION_LINSEN_FLOAT_API							(1)
/* x86 float, linsen float, AiBaseFloat */
#define AI_PRODUCT_OPTION_FLOAT_MODEL_CONSIST_CHECK					(0)	
/* lnet */
#define AI_PRODUCT_OPTION_LNET_PACKET								(1)
/* image */
#define AI_PRODUCT_OPTION_VISION_NONE								(1)
#define AI_PRODUCT_OPTION_VISION_OPENCV								(0)

/*------------------------- Glboal Macro Definition -------------------------*/

#if (AI_PRODUCT_OPTION_WEIGHTS_ADJUST == 1)
#define AI_NET_WEIGHTS_MUL_VALUE									((FLOAT32_T)1.0)
#endif

/*------------------------- Glboal Macro Definition -------------------------*/
#define IA_BASE_FLASE												(0)
#define IA_BASE_TRUE												(1)

/*------------------------- Base Macro Definition -------------------------*/
/* hware */
#define AI_BASE_HWARE_PN_LENGTH                        	(16)
#if (AI_PRODUCT_BOARD_NAME == AI_PRODUCT_BOARD_NAME_X86)
#define AI_BASE_HWARE_PN_DEFAULT                       	("PN_AI_X86")
#endif
#if (AI_PRODUCT_BOARD_NAME == AI_PRODUCT_BOARD_NAME_SISCTECH)
#define AI_BASE_HWARE_PN_DEFAULT                       	("PN_AI_0")
#endif
#define AI_BASE_HWARE_SN_LENGTH                        	(16)
#define AI_BASE_HWARE_SN_DEFAULT                       	("0000000000000000")
#define AI_BASE_HWARE_VER_LENGTH                       	(16)
#define AI_BASE_HWARE_VER_DEFAULT                      	("V100")
#define AI_BASE_HWARE_COM_INVALID						(0x00)
#define AI_BASE_HWARE_COM_LOCAL                        	(0x01)
#define AI_BASE_HWARE_COM_RS232                        	(0x02)
#define AI_BASE_HWARE_COM_CDC 	                     	(0x04)
#define AI_BASE_HWARE_VALID                            	(1)
#define AI_BASE_HWARE_INVALID                          	(0)
/* sware */
#define AI_BASE_SWARE_VER_LENGTH                       	(16)
#define AI_BASE_SWARE_VER_DEFAULT                      	("V100")
#define AI_BASE_SWARE_UNIT_TYPE_BASE					(0x01)
#define AI_BASE_SWARE_UNIT_TYPE_BOOT                	(0x02)
#define AI_BASE_SWARE_UNIT_TYPE_MANAGE					(0x04)
#define AI_BASE_SWARE_UNIT_TYPE_SERVER					(0x08)
#define AI_BASE_SWARE_UNIT_TYPE_SLAVE					(0x10)  /* master-slave */
#define AI_BASE_SWARE_UNIT_TYPE_BACKUP					(0x20)  /* host-backup */
#define AI_BASE_SWARE_ADDR_UNIT_MASK					(0xE0)
#define AI_BASE_SWARE_ADDR_UNIT_BASE					(0x20)
#define AI_BASE_SWARE_ADDR_UNIT_BOOT					(0x40)
#define AI_BASE_SWARE_ADDR_UNIT_MANAGE					(0x60)
#define AI_BASE_SWARE_ADDR_UNIT_SERVER					(0x80)
#if (AI_PRODUCT_BOARD_NAME == AI_PRODUCT_BOARD_NAME_X86)
#define AI_BASE_SWARE_ADDR_SERVER_IO_SW					(0x00)
#endif
#if (AI_PRODUCT_BOARD_NAME == AI_PRODUCT_BOARD_NAME_SISCTECH)
#define AI_BASE_SWARE_ADDR_SERVER_IO_SW					(0x10)
#endif
#define AI_BASE_SWARE_ADDR_TYPE_INVALID					(0)
#define AI_BASE_SWARE_ADDR_TYPE_HW                     	(1)
#define AI_BASE_SWARE_ADDR_TYPE_SW                     	(2)
#define AI_BASE_SWARE_ADDR_TYPE                        	(AI_BASE_SWARE_ADDR_TYPE_SW)
/* unit */
#define AI_BASE_UNIT_P232                        		(1)
#define AI_BASE_UNIT_PCDC                        		(2)
#if (AI_PRODUCT_BOARD_NAME == AI_PRODUCT_BOARD_NAME_X86)
#define AI_BASE_UNIT_DEFAULT                           	(AI_BASE_UNIT_PCDC)
#endif
#if (AI_PRODUCT_BOARD_NAME == AI_PRODUCT_BOARD_NAME_SISCTECH)
#define AI_BASE_UNIT_DEFAULT                           	(AI_BASE_UNIT_PCDC)
#endif
#define AI_BASE_UNIT_VALID                             	(1)
#define AI_BASE_UNIT_INVALID                           	(0)
/* hconfig */
#define AI_BASE_HCONFIG_VALID                          	('H')
/* sconfig */
#define AI_BASE_SCONFIG_VALID                          	('S')
/* unit */
#if  (AI_BASE_UNIT_DEFAULT == AI_BASE_UNIT_PCDC)
#define AI_BASE_HWARE_COM_CDC_VALID                  	(AI_BASE_HWARE_VALID)
#define AI_BASE_HWARE_COM_RS23_VALID                  	(AI_BASE_HWARE_INVALID)
#define AI_BASE_SWARE_COM_MANAGE_SERVER					(AI_BASE_HWARE_COM_CDC)
#define AI_BASE_SWARE_UNIT_TYPE                        	(AI_BASE_SWARE_UNIT_TYPE_BASE | AI_BASE_SWARE_UNIT_TYPE_MANAGE)
#define AI_BASE_SWARE_ADDR_TYPE_SERVER					(AI_BASE_SWARE_ADDR_TYPE_INVALID)
#define AI_BASE_SWARE_ADDR_TYPE_MANAGE					(AI_BASE_SWARE_ADDR_TYPE_SW)
#endif

/*------------------------- Basic Macro Definition --------------------------*/
/* total rom address */
#define AI_BASE_ROM_ADDR_START                         (0x08000000)
#define AI_BASE_ROM_LENGTH                             (256*1024)
#define AI_BASE_ROM_ADDR_END                           (AI_BASE_ROM_ADDR_START + AI_BASE_ROM_LENGTH - 1)
/* boot code and data rom address */
#define AI_BASE_ROM_BOOT_CODE_ADDR_START               (AI_BASE_ROM_ADDR_START)
#define AI_BASE_ROM_BOOT_CODE_LENGTH                   (32*1024)
#define AI_BASE_ROM_BOOT_CODE_ADDR_END                 (AI_BASE_ROM_BOOT_CODE_ADDR_START + AI_BASE_ROM_BOOT_CODE_LENGTH - 1)
#define AI_BASE_ROM_BOOT_CONFIG_ADDR_START             (AI_BASE_ROM_BOOT_CODE_ADDR_END + 1)
#define AI_BASE_ROM_BOOT_CONFIG_LENGTH                 (4*1024)
#define AI_BASE_ROM_BOOT_CONFIG_ADDR_END               (AI_BASE_ROM_BOOT_CONFIG_ADDR_START + AI_BASE_ROM_BOOT_CONFIG_LENGTH -1)
/* boot configuration address */
#define AI_BOOT_BASE_ROM_CONFIG_DATA_ADDR_START        (AI_BASE_ROM_BOOT_CONFIG_ADDR_START)
#define AI_BOOT_BASE_ROM_CONFIG_DATA_LENGTH            (1*1024)
#define AI_BOOT_BASE_ROM_CONFIG_DATA_ADDR_END          (AI_BOOT_BASE_ROM_CONFIG_DATA_ADDR_START + AI_BOOT_BASE_ROM_CONFIG_DATA_LENGTH - 1)
#define AI_BOOT_CENTER_ROM_CONFIG_DATA_ADDR_START      (AI_BOOT_BASE_ROM_CONFIG_DATA_ADDR_END)
#define AI_BOOT_CENTER_ROM_CONFIG_DATA_LENGTH          (1*1024)
#define AI_BOOT_CENTER_ROM_CONFIG_DATA_ADDR_END        (AI_BOOT_CENTER_ROM_CONFIG_DATA_ADDR_START + AI_BOOT_CENTER_ROM_CONFIG_DATA_LENGTH - 1)
#define AI_BOOT_ROM_CONFIG_DATA_ADDR_START             (AI_BOOT_CENTER_ROM_CONFIG_DATA_ADDR_END)
#define AI_BOOT_ROM_CONFIG_DATA_LENGTH                 (1*1024)
#define AI_BOOT_ROM_CONFIG_DATA_ADDR_END               (AI_BOOT_ROM_CONFIG_DATA_ADDR_START + AI_BOOT_ROM_CONFIG_DATA_LENGTH - 1)
/* monitor code and data rom address */
#define AI_BACKUP_BASE_ROM_MONITOR_CONFIG_ADDR_START   (AI_BASE_ROM_BOOT_CONFIG_ADDR_END + 1)
#define AI_BACKUP_BASE_ROM_MONITOR_CONFIG_LENGTH       (6*1024)
#define AI_BACKUP_BASE_ROM_MONITOR_CONFIG_ADDR_END     (AI_BACKUP_BASE_ROM_MONITOR_CONFIG_ADDR_START + AI_BACKUP_BASE_ROM_MONITOR_CONFIG_LENGTH -1)
#define AI_BASE_ROM_MONITOR_CONFIG_ADDR_START          (AI_BACKUP_BASE_ROM_MONITOR_CONFIG_ADDR_END + 1)
#define AI_BASE_ROM_MONITOR_CONFIG_LENGTH              (6*1024)
#define AI_BASE_ROM_MONITOR_CONFIG_ADDR_END            (AI_BASE_ROM_MONITOR_CONFIG_ADDR_START + AI_BASE_ROM_MONITOR_CONFIG_LENGTH -1)
#define AI_BASE_ROM_MONITOR_SOC_CONFIG_ADDR_START      (AI_BASE_ROM_MONITOR_CONFIG_ADDR_END + 1)
#define AI_BASE_ROM_MONITOR_SOC_CONFIG_LENGTH          (8*1024)
#define AI_BASE_ROM_MONITOR_SOC_CONFIG_ADDR_END        (AI_BASE_ROM_MONITOR_SOC_CONFIG_ADDR_START + AI_BASE_ROM_MONITOR_SOC_CONFIG_LENGTH -1)
#define AI_BASE_ROM_MONITOR_CODE_ADDR_START            (AI_BASE_ROM_MONITOR_SOC_CONFIG_ADDR_END + 1)
#define AI_BASE_ROM_MONITOR_CODE_LENGTH                (200*1024)
#define AI_BASE_ROM_MONITOR_CODE_ADDR_END              (AI_BASE_ROM_MONITOR_CODE_ADDR_START + AI_BASE_ROM_MONITOR_CODE_LENGTH - 1)
/* configuration address */
#define AI_BASE_ROM_CONFIG_DATA_ADDR_START             (AI_BASE_ROM_MONITOR_CONFIG_ADDR_START)
#define AI_BASE_ROM_CONFIG_DATA_LENGTH                 (1*1024)
#define AI_BASE_ROM_CONFIG_DATA_ADDR_END               (AI_BASE_ROM_CONFIG_DATA_ADDR_START + AI_BASE_ROM_CONFIG_DATA_LENGTH - 1)
#define AI_NETWORK_ROM_CONFIG_DATA_ADDR_START          (AI_BASE_ROM_CONFIG_DATA_ADDR_END + 1)
#define AI_NETWORK_ROM_CONFIG_DATA_LENGTH              (1*1024)
#define AI_NETWORK_ROM_CONFIG_DATA_ADDR_END            (AI_NETWORK_ROM_CONFIG_DATA_ADDR_START + AI_NETWORK_ROM_CONFIG_DATA_LENGTH - 1)
#define AI_CONTROL_ROM_CONFIG_DATA_ADDR_START          (AI_NETWORK_ROM_CONFIG_DATA_ADDR_END + 1)
#define AI_CONTROL_ROM_CONFIG_DATA_LENGTH              (1*1024)
#define AI_CONTROL_ROM_CONFIG_DATA_ADDR_END            (AI_CONTROL_ROM_CONFIG_DATA_ADDR_START + AI_CONTROL_ROM_CONFIG_DATA_LENGTH - 1)
#define AI_CENTER_ROM_CONFIG_DATA_ADDR_START           (AI_CONTROL_ROM_CONFIG_DATA_ADDR_END + 1)
#define AI_CENTER_ROM_CONFIG_DATA_LENGTH               (1*1024)
#define AI_CENTER_ROM_CONFIG_DATA_ADDR_END             (AI_CENTER_ROM_CONFIG_DATA_ADDR_START + AI_CENTER_ROM_CONFIG_DATA_LENGTH - 1)
#define AI_MANAGE_ROM_CONFIG_DATA_ADDR_START           (AI_CENTER_ROM_CONFIG_DATA_ADDR_END + 1)
#define AI_MANAGE_ROM_CONFIG_DATA_LENGTH               (1*1024)
#define AI_MANAGE_ROM_CONFIG_DATA_ADDR_END             (AI_MANAGE_ROM_CONFIG_DATA_ADDR_START + AI_MANAGE_ROM_CONFIG_DATA_LENGTH - 1)
#define AI_BASE_ROM_CONFIG_SOFT_ADDR_START             (AI_MANAGE_ROM_CONFIG_DATA_ADDR_END + 1)
#define AI_BASE_ROM_CONFIG_SOFT_LENGTH                 (1*1024)
#define AI_BASE_ROM_CONFIG_SOFT_ADDR_END               (AI_BASE_ROM_CONFIG_SOFT_ADDR_START + AI_BASE_ROM_CONFIG_SOFT_LENGTH - 1)
/* flash */
#define AI_BASE_FLASH_PAGE_SIZE                        (0x800)
#define AI_BASE_FLASH_ADDR_START                       (AI_BASE_ROM_ADDR_START)
#define AI_BASE_FLASH_ADDR_END                         (AI_BASE_ROM_ADDR_END)

/* update */
#if ((AI_PRODUCT_SOFT_NAME == AI_PRODUCT_SOFT_NAME_SERVER) || (AI_PRODUCT_SOFT_NAME == AI_PRODUCT_SOFT_NAME_MONITOR))
#define AI_BASE_UPDATE_PROTECT_ADDRESS_MIN             (AI_BACKUP_BASE_ROM_MONITOR_CONFIG_ADDR_START)
#define AI_BASE_UPDATE_PROTECT_ADDRESS_MAX             (AI_BASE_ROM_MONITOR_CODE_ADDR_END)
#define AI_BASE_UPDATE_LENGTH_MAX                      (64)
#endif
#if (AI_PRODUCT_SOFT_NAME == AI_PRODUCT_SOFT_NAME_BOOT)
#define AI_BASE_UPDATE_PROTECT_ADDRESS_MIN             (AI_BASE_ROM_BOOT_CODE_ADDR_START)
#define AI_BASE_UPDATE_PROTECT_ADDRESS_MAX             (AI_BASE_ROM_BOOT_CONFIG_ADDR_END)
#define AI_BASE_UPDATE_LENGTH_MAX                      (64)
#endif

/*------------------------- Base Lnet Macro Definition -------------------------*/
/* lnet link*/
#define AI_BASE_LNET_LINK_BUFFER_LENGTH					(256)
#define AI_BASE_LNET_LINK_BUFFER_MASK					(0xFF)
#define AI_BASE_LNET_LINK_TX_IDLE						(0)
#define AI_BASE_LNET_LINK_TX_BUSY						(1)
#define AI_BASE_LNET_LINK_RX_TIMEOUT					(1000)
/* lnet modbus */
#if (AI_PRODUCT_OPTION_LNET_MODBUS == 1)
#define AI_BASE_LENT_PACKET_OPTIMIZE					(0)
#define AI_BASE_LNET_PACKET_SWARE_ADDR_SERVER_IO_SW	(0x10)
#define AI_BASE_LNET_PACKET_SWARE_BASE_ADDR				(0x20)
#define AI_BASE_LNET_PACKET_STX_LENGTH					(0)
#define AI_BASE_LNET_PACKET_SOURCE_ADDR_LENGTH			(1)
#define AI_BASE_LNET_PACKET_DEST_ADDR_LENGTH			(1)
#define AI_BASE_LNET_PACKET_FCODE_LENGTH				(1)
#define AI_BASE_LENT_PACKET_FCODE_MASK					(0x7F)
#define AI_BASE_LNET_PACKET_FCODE_READ_COILS			(0x01)
#define AI_BASE_LNET_PACKET_FCODE_READ_SWITCHS			(0x02)
#define AI_BASE_LNET_PACKET_FCODE_READ_HOLD_REGS		(0x03)
#define AI_BASE_LNET_PACKET_FCODE_READ_INPUT_REGS		(0x04)
#define AI_BASE_LNET_PACKET_FCODE_WRITE_COIL			(0x05)
#define AI_BASE_LNET_PACKET_FCODE_WRITE_HOLD_REG		(0x06)
#define AI_BASE_LNET_PACKET_FCODE_WRITE_COILS			(0x0F)
#define AI_BASE_LNET_PACKET_FCODE_WRITE_HOLD_REGS		(0x10)
#define AI_BASE_LNET_PACKET_FCODE_READ_FILE_RECORD		(0x14)
#define AI_BASE_LNET_PACKET_FCODE_WRITE_MASK_REG		(0x16)
#define AI_BASE_LNET_PACKET_FCODE_RW_REGS				(0x17)
#define AI_BASE_LNET_PACKET_FCODE_READ_DEVICE			(0x1B)
#define AI_BASE_LNET_PACKET_REG_START_ADDR_LENGTH		(2)
#define AI_BASE_LNET_PACKET_REG_VALUE_LENGTH			(2)
#define AI_BASE_LNET_PACKET_REG_NUMBER_LENGTH			(2)
#define AI_BASE_LNET_PACKET_FCODE_ERROR_MIN				(0x80)
#define AI_BASE_LNET_PACKET_ECODE_LENGTH				(1)
#define AI_BASE_LNET_PACKET_ECODE_FUNCTION_ERROR		(0x01)
#define AI_BASE_LNET_PACKET_ECODE_REG_ERROR				(0x02)
#define AI_BASE_LNET_PACKET_ECODE_DATA_ERROR			(0x03)
#define AI_BASE_LNET_PACKET_ECODE_DEVICE_ERROR			(0x04)
#define AI_BASE_LNET_PACKET_ECODE_CONFIRM_ERROR			(0x05)
#define AI_BASE_LNET_PACKET_ECODE_BUSY_ERROR			(0x06)
#define AI_BASE_LNET_PACKET_ECODE_CRC_ERROR				(0x08)
#define AI_BASE_LNET_PACKET_ECODE_GATEWAY_DIR_ERROR		(0x0A)
#define AI_BASE_LNET_PACKET_ECODE_GATEWAY_RES_ERROR		(0x0B)
#define AI_BASE_LNET_PACKET_LENGTH_LENGTH				(1)
#define AI_BASE_LNET_PACKET_CHECKSUM_LENGTH				(2)
#define AI_BASE_LNET_PACKET_ETX_LENGTH					(0)
#define AI_BASE_LNET_PACKET_LINK_LENGTH_MIN				(AI_BASE_LNET_PACKET_STX_LENGTH+AI_BASE_LNET_PACKET_DEST_ADDR_LENGTH+AI_BASE_LNET_PACKET_FCODE_LENGTH+AI_BASE_LNET_PACKET_ECODE_LENGTH+AI_BASE_LNET_PACKET_ETX_LENGTH)
#define AI_BASE_LNET_PACKET_HEAD_LENGTH					(AI_BASE_LNET_PACKET_STX_LENGTH)
#define AI_BASE_LNET_PACKET_TAIL_LENGTH					(AI_BASE_LNET_PACKET_CHECKSUM_LENGTH + AI_BASE_LNET_PACKET_ETX_LENGTH)
#define AI_BASE_LNET_PACKET_HEAD_TAIL_LENGTH			(AI_BASE_LNET_PACKET_HEAD_LENGTH + AI_BASE_LNET_PACKET_TAIL_LENGTH)
#define AI_BASE_LNET_PACKET_COMMAND_FLAG_RECV			(0)
#define AI_BASE_LNET_PACKET_COMMAND_FLAG_SEND			(1)
#define AI_BASE_LNET_PACKET_COMMAND_MASK				(0x7F)
#define AI_BASE_LNET_PACKET_COMMAND_SHIFT				(0)
#define AI_BASE_LNET_PACKET_FIELD_MAX					(125)
#define AI_BASE_LNET_PACKET_COMMAND_RESPONSE_INC		(0)
#define AI_BASE_LNET_PACKET_COMMAND_RETCODE_ERROR		(1)
#define AI_BASE_LNET_PACKET_COMMAND_RETCODE_SHIFT		(7)
#define AI_BASE_LNET_PACKET_COMMAND_RETCODE_MASK		(0x80)
#define AI_BASE_LNET_PACKET_FIELD_VALID					(1)
#define AI_BASE_LNET_PACKET_FIELD_INVALID				(0)
#define AI_BASE_LNET_PACKET_DATA_VALUE_VALID			(1)
#define AI_BASE_LNET_PACKET_DATA_VALUE_INVALID			(0)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_ZERO			(0)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_BYTE			(1)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_SHORT		(2)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_WORD			(4)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_DWORD		(8)
#define AI_BASE_LNET_PACKET_COMMAND_FLAG_RECV			(0)
#define AI_BASE_LNET_PACKET_COMMAND_FLAG_SEND			(1)
#define AI_BASE_LNET_PACKET_COMMAND_RETCODE_SUCCESS		(0)
#define AI_BASE_LNET_PACKET_COMMAND_READ_REQUEST		(0)
#define AI_BASE_LNET_PACKET_COMMAND_READ_RESPONSE		(1)
#define AI_BASE_LNET_PACKET_COMMAND_WRITE_REQUEST		(2)
#define AI_BASE_LNET_PACKET_COMMAND_WRITE_RESPONSE		(3)
#endif
/* lnet packet */
#define AI_BASE_LNET_ESCAPE_NONE						(0)
#define AI_BASE_LNET_ESCAPE_HLUART						(1)
#define AI_BASE_LNET_ESCAPE_HLUART_FLAG_MASK			(0xAA)
#define AI_BASE_LNET_ESCAPE_HLUART_FIRST_FLAG			(0x22)
#define AI_BASE_LNET_ESCAPE_HLUART_SECOND_FLAG			(0x88)
#define AI_BASE_LNET_ESCAPE_HLUART_DATA_MASK			(0x55)
#define AI_BASE_LNET_ESCAPE_HLUART_FIRST_DATA_SHIFT		(1)
#define AI_BASE_LNET_ESCAPE_HLUART_SECOND_DATA_SHIFT	(0)
#define AI_BASE_LENT_ESCAPE_RATE						(2)
#define AI_BASE_LNET_PACKET_BUFFER_LENGTH				((AI_BASE_LENT_ESCAPE_RATE+1)*AI_BASE_LNET_LINK_BUFFER_LENGTH)
#define AI_BASE_LENT_PACKET_RX_START					(AI_BASE_LNET_PACKET_BUFFER_LENGTH - AI_BASE_LENT_ESCAPE_RATE*AI_BASE_LNET_LINK_BUFFER_LENGTH)
#define AI_BASE_LNET_PACKET_TX_START					(AI_BASE_LNET_PACKET_BUFFER_LENGTH - AI_BASE_LENT_ESCAPE_RATE*AI_BASE_LNET_LINK_BUFFER_LENGTH)
#if (AI_PRODUCT_OPTION_LNET_PACKET == 1)
#define AI_BASE_LNET_PACKET_STX							(0x02)
#define AI_BASE_LNET_PACKET_ETX							(0x03)
#define AI_BASE_LNET_PACKET_STX_LENGTH					(1)
#define AI_BASE_LNET_PACKET_LENGTH_LENGTH				(2)
#define AI_BASE_LNET_PACKET_SEQUENCE_LENGTH				(1)
#define AI_BASE_LNET_PACKET_SOURCE_ADDR_LENGTH			(1)
#define AI_BASE_LNET_PACKET_DEST_ADDR_LENGTH			(1)
#define AI_BASE_LNET_PACKET_COMMAND_LENGTH				(1)
#define AI_BASE_LNET_PACKET_CHECKSUM_LENGTH				(2)
#define AI_BASE_LNET_PACKET_ETX_LENGTH					(1)
#define AI_BASE_LNET_PACKET_HEAD_LENGTH					(AI_BASE_LNET_PACKET_STX_LENGTH + AI_BASE_LNET_PACKET_LENGTH_LENGTH)
#define AI_BASE_LNET_PACKET_TAIL_LENGTH					(AI_BASE_LNET_PACKET_CHECKSUM_LENGTH + AI_BASE_LNET_PACKET_ETX_LENGTH)
#define AI_BASE_LNET_PACKET_HEAD_TAIL_LENGTH			(AI_BASE_LNET_PACKET_HEAD_LENGTH + AI_BASE_LNET_PACKET_TAIL_LENGTH)
#define AI_BASE_LNET_PACKET_NET_LENGTH					(AI_BASE_LNET_PACKET_SEQUENCE_LENGTH + AI_BASE_LNET_PACKET_SOURCE_ADDR_LENGTH + AI_BASE_LNET_PACKET_DEST_ADDR_LENGTH + AI_BASE_LNET_PACKET_COMMAND_LENGTH)
#define AI_BASE_LNET_PACKET_LENGTH_MIN					(AI_BASE_LNET_PACKET_NET_LENGTH)
#define AI_BASE_LNET_PACKET_LINK_LENGTH_MIN				(AI_BASE_LNET_PACKET_HEAD_TAIL_LENGTH + AI_BASE_LNET_PACKET_LENGTH_MIN)
#define AI_BASE_LNET_PACKET_LENGTH_MAX					(AI_BASE_LNET_LINK_BUFFER_LENGTH - AI_BASE_LNET_PACKET_HEAD_TAIL_LENGTH)
#define AI_BASE_LNET_PACKET_FIELD_MAX					(64)
#define AI_BASE_LNET_PACKET_FIELD_MAP_LENGTH			(1)
#define AI_BASE_LNET_PACKET_INDEX_LENGTH_MAP			(1)
#define AI_BASE_LNET_PACKET_INDEX_LENGTH_MASK			(0x01)
#define AI_BASE_LNET_PACKET_INDEX_LENGTH_SHIFT			(0)
#define AI_BASE_LNET_PACKET_INDEX_LENGTH_ADD			(1)
#define AI_BASE_LNET_PACKET_INDEX_LENGTH_BYTE			(1)
#define AI_BASE_LNET_PACKET_INDEX_LENGTH_SHORT			(2)
#define AI_BASE_LNET_PACKET_SUB_INDEX_VALID_MASK		(0x02)
#define AI_BASE_LNET_PACKET_SUB_INDEX_VALID_SHIFT		(1)
#define AI_BASE_LNET_PACKET_SUB_INDEX_VALID_ADD			(0)
#define AI_BASE_LNET_PACKET_SUB_INDEX_VALID				(1)
#define AI_BASE_LNET_PACKET_SUB_INDEX_INVALID			(0)
#define AI_BASE_LNET_PACKET_SUB_INDEX_LENGTH_MASK		(0x0C)
#define AI_BASE_LNET_PACKET_SUB_INDEX_LENGTH_SHIFT		(2)
#define AI_BASE_LNET_PACKET_SUB_INDEX_LENGTH_ADD		(1)
#define AI_BASE_LNET_PACKET_SUB_INDEX_LENGTH_DIV		(2)
#define AI_BASE_LNET_PACKET_SUB_INDEX_LENGTH_BYTE		(1)
#define AI_BASE_LNET_PACKET_SUB_INDEX_LENGTH_SHORT		(2)
#define AI_BASE_LNET_PACKET_SUB_INDEX_LENGTH_THREE		(3)
#define AI_BASE_LNET_PACKET_SUB_INDEX_LENGTH_WORD		(4)
#define AI_BASE_LNET_PACKET_SUB_INDEX_LENGTH_DWORD		(8)
#define AI_BASE_LNET_PACKET_SUB_INDEX_MAP_BYTE			(0)
#define AI_BASE_LNET_PACKET_SUB_INDEX_MAP_SHORT			(1)
#define AI_BASE_LNET_PACKET_SUB_INDEX_MAP_THREE			(2)
#define AI_BASE_LNET_PACKET_SUB_INDEX_MAP_WORD			(2)
#define AI_BASE_LNET_PACKET_SUB_INDEX_MAP_DWORD			(3)
#define AI_BASE_LNET_PACKET_SUB_INDEX_DEFAULT			(0)
#define AI_BASE_LNET_PACKET_SUB_INDEX_MULTI_SUPPORT		(1)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_VALID_MASK	(0x10)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_VALID_SHIFT	(4)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_VALID_ADD	(0)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_VALID		(1)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_INVALID		(0)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_LENGTH		(1)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_DEFAULT		(1)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_ZERO			(0)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_BYTE			(1)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_SHORT		(2)
#define AI_BASE_LNET_PACKET_DATA_TYPE_SIZE_WORD			(4)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_VALID_MASK		(0x20)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_VALID_SHIFT		(5)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_VALID_ADD		(0)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_VALID			(1)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_INVALID			(0)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_LENGTH_MASK		(0x40)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_LENGTH_SHIFT	(6)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_LENGTH_ADD		(1)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_LENGTH_BYTE		(1)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_LENGTH_SHORT	(2)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_DEFAULT			(1)
#define AI_BASE_LNET_PACKET_DATA_NUMBER_MAX				(128)
#define AI_BASE_LNET_PACKET_DATA_VALUE_VALID_MASK		(0x80)
#define AI_BASE_LNET_PACKET_DATA_VALUE_VALID_SHIFT		(7)
#define AI_BASE_LNET_PACKET_DATA_VALUE_VALID_ADD		(0)
#define AI_BASE_LNET_PACKET_DATA_VALUE_VALID			(1)
#define AI_BASE_LNET_PACKET_DATA_VALUE_INVALID			(0)
#define AI_BASE_LNET_PACKET_DATA_LENGTH_AS_ADDR			(8)
#define AI_BASE_LNET_PACKET_FIELD_VALID					(1)
#define AI_BASE_LNET_PACKET_FIELD_INVALID				(0)
#define AI_BASE_LNET_PACKET_COMMAND_MASK				(0x0F)
#define AI_BASE_LNET_PACKET_COMMAND_SHIFT				(0)
#define AI_BASE_LNET_PACKET_COMMAND_READ_REQUEST		(0)
#define AI_BASE_LNET_PACKET_COMMAND_READ_RESPONSE		(1)
#define AI_BASE_LNET_PACKET_COMMAND_WRITE_REQUEST		(2)
#define AI_BASE_LNET_PACKET_COMMAND_WRITE_RESPONSE		(3)
#define AI_BASE_LNET_PACKET_COMMAND_RESPONSE_INC		(1)
#define AI_BASE_LNET_PACKET_COMMAND_RETCODE_SUCCESS		(0)
#define AI_BASE_LNET_PACKET_COMMAND_RETCODE_ERROR		(1)
#define AI_BASE_LNET_PACKET_COMMAND_RETCODE_SHIFT		(4)
#define AI_BASE_LNET_PACKET_COMMAND_RETCODE_MASK		(0xF0)
#define AI_BASE_LNET_PACKET_COMMAND_FLAG_RECV			(0)
#define AI_BASE_LNET_PACKET_COMMAND_FLAG_SEND			(1)
#define AI_BASE_LNET_PACKET_OPERATE_READ				(1)
#define AI_BASE_LNET_PACKET_OPERATE_WRITE				(2)
#define AI_BASE_LNET_PACKET_OPERATE_READ_WRITE			(3)
#define AI_BASE_LNET_PACKET_BYTE_ONE					(0xFF)
#define AI_BASE_LNET_PACKET_BYTE_TWO					(0xFFFF)
#define AI_BASE_LNET_PACKET_BYTE_THREE					(0xFFFFFF)
#define AI_BASE_LNET_PACKET_BYTE_FOUR					(0xFFFFFFFF)
#define AI_BASE_LNET_PACKET_BYTE_EIGHT					(0xFFFFFFFFFFFFFFFF)
#endif
/* phy */
#define AI_BASE_LENT_PHY_NAME_LENGTH					(16)
#define AI_BASE_LNET_PHY_NAME_RS232						("rs232")
#define AI_BASE_LNET_PHY_NAME_HUART						("huart")
#define AI_BASE_LNET_PHY_NAME_LUART						("luart")

/*------------------------- Boot Macro Definition FP16 ----------------------*/
#define AI_BASE_FLOAT_FP16								(1)
#define AI_BASE_FLOAT_FP32								(1)
#define AI_BASE_FLOAT_FP64								(1)

/*------------------------- Boot Macro Definition detect --------------------*/
/* ai base module root */
#define AI_BASE_DETECT_ROOT_AVERAGE								(0)
#define AI_BASE_DETECT_ROOT_YOLO								(1)
#define AI_BASE_DETECT_ROOT_VOXEL								(2)
#define AI_BASE_DETECT_ROOT_SUPER								(3)
#define AI_BASE_DETECT_ROOT_DETECTOR							(4)
#define AI_BASE_DETECT_ROOT_DETECT								(5)
#define AI_BASE_DETECT_ROOT_CIFAR								(6)
#define AI_BASE_DETECT_ROOT_GO									(7)
#define AI_BASE_DETECT_ROOT_RNN									(8)
#define AI_BASE_DETECT_ROOT_VID									(9)
#define AI_BASE_DETECT_ROOT_COCO								(10)
#define AI_BASE_DETECT_ROOT_CLASSIFY							(11)
#define AI_BASE_DETECT_ROOT_CLASSIFIER							(12)
#define AI_BASE_DETECT_ROOT_ART									(13)
#define AI_BASE_DETECT_ROOT_TAG									(14)
#define AI_BASE_DETECT_ROOT_COMPARE								(15)
#define AI_BASE_DETECT_ROOT_DICE								(16)
#define AI_BASE_DETECT_ROOT_WRITING								(17)
#define AI_BASE_DETECT_ROOT_3D									(18)
#define AI_BASE_DETECT_ROOT_TEST								(19)
#define AI_BASE_DETECT_ROOT_CAPTCHA								(20)
#define AI_BASE_DETECT_ROOT_NIGHTMARE							(21)
#define AI_BASE_DETECT_ROOT_RGBGR								(22)
#define AI_BASE_DETECT_ROOT_RESET								(23)
#define AI_BASE_DETECT_ROOT_DENORMALIZE							(24)
#define AI_BASE_DETECT_ROOT_RESCALE								(25)
#define AI_BASE_DETECT_ROOT_OPS									(26)
#define AI_BASE_DETECT_ROOT_SPEED								(27)
#define AI_BASE_DETECT_ROOT_ONEOFF								(28)
#define AI_BASE_DETECT_ROOT_PARTIAL								(29)
#define AI_BASE_DETECT_ROOT_VISUALIZE							(30)
#define AI_BASE_DETECT_ROOT_IMTEST								(31)
/* dectect phase */
#define AI_BASE_DETECT_PHASE_IDENT								(0)
#define AI_BASE_DETECT_PHASE_TRAIN								(1)
#define AI_BASE_DETECT_PHASE_VALID								(2)
#define AI_BASE_DETECT_PHASE_RECALL								(3)
#define AI_BASE_DETECT_PHASE_MAP								(4)
#define AI_BASE_DETECT_PHASE_CALC_ANCHORS						(5)
#define AI_BASE_DETECT_PHASE_DEMO								(6)
/* detect datasets */
#define AI_BASE_DETECT_DATASETS_COCO							(0)
/* detect net */
#define AI_BASE_DETECT_NET_YOLOV3								(0)
/* detect weights */
#define AI_BASE_DETECT_WEIGHTS_YOLOV3							(0)
#define AI_BASE_DETECT_WEIGHTS_YOLOV3_TINY						(1)
/* detect source */
#define AI_BASE_DETECT_SOURCE_IMAGE								(0)
#define AI_BASE_DETECT_SOURCE_VIDEO								(1)
#define AI_BASE_DETECT_SOURCE_CAMERA							(2)
/* detect ident confidence threshold */
#define AI_BASE_DETECT_IDENT_CONFIDENCE_THRESHOLD_DEFAULT		((float)0.25)
/* detect ident option */
#define AI_BASE_DETECT_IDENT_DONT_SHOW							(IA_BASE_FALSE)
#define AI_BASE_DETECT_IDENT_SHOW								(IA_BASE_TRUE)
/* detect ident option */
#define AI_BASE_DETECT_IDENT_MAP								(0)
#define AI_BASE_DETECT_IDENT_CHECK_MISTAKES						(0)
#define AI_BASE_DETECT_IDENT_HTTP_PORT							(0)
#define AI_BASE_DETECT_IDENT_OUT_FILENAME						(0)
#define AI_BASE_DETECT_IDENT_OUT								(0)
#define AI_BASE_DETECT_IDENT_PREFIX								(0)
#define AI_BASE_DETECT_IDENT_IOU_THRESH							(0)
#define AI_BASE_DETECT_IDENT_HIER								(0)
#define AI_BASE_DETECT_IDENT_C									(0)
#define AI_BASE_DETECT_IDENT_S									(0)
#define AI_BASE_DETECT_IDENT_NUM_OF_CLUSTERS					(0)
#define AI_BASE_DETECT_IDENT_WIDTH								(0)
#define AI_BASE_DETECT_IDENT_HEIGHT								(0)
#define AI_BASE_DETECT_IDENT_EXT_OUTPUT							(0)
#define AI_BASE_DETECT_IDENT_SAVE_LABELS						(0)
#define AI_BASE_DETECT_IDENT_GPUS								(0)
#define AI_BASE_DETECT_IDENT_CLEAR								(0)

/*------------------------- Boot Macro Definition ---------------------------*/

/*------------------------- Manage Macro Definition -------------------------*/

/*------------------------- Server Macro Definition -------------------------*/
#define IDENT_THREAD_STOP						(0)
#define IDENT_THREAD_START						(1)
#define IDENT_THREAD_EXIT_START					(2)
#define IDENT_THREAD_EXIT_FINISH				(3)

#define SERIAL_THREAD_SEND_STOP					(0)
#define SERIAL_THREAD_SEND_START				(1)
#define SERIAL_THREAD_SEND_EXIT_START			(2)
#define SERIAL_THREAD_SEND_EXIT_FINISH			(3)

#define SERIAL_THREAD_RECV_STOP					(0)
#define SERIAL_THREAD_RECV_START				(1)
#define SERIAL_THREAD_RECV_EXIT_START			(2)
#define SERIAL_THREAD_RECV_EXIT_FINISH			(3)

#define COMMAND_THREAD_STOP						(0)
#define COMMAND_THREAD_START					(1)
#define COMMAND_THREAD_EXIT_START				(2)
#define COMMAND_THREAD_EXIT_FINISH				(3)
#define COMMAND_THREAD_STOP_USER				(4)

#define DEVICE_DATA_ERROR						(0)
#define DEVICE_DATA_START						(1)
#define DEVICE_DATA_COM_OPEN					(2)
#define DEVICE_DATA_SEND						(3)
#define DEVICE_DATA_RECV						(4)
#define DEVICE_DATA_COM_CLOSE					(5)
#define DEVICE_DATA_END							(6)

#define DEVICE_DATA_FIELD_NUM_MAX				(64)
#define SERIAL_PACKET_LENGTH_MAX				(2048)

#define DEVICE_INFO_SEND_STATE_ERROR			(0)
#define DEVICE_INFO_SEND_STATE_START			(1)
#define DEVICE_INFO_SEND_STATE_COM_OPEN			(2)
#define DEVICE_INFO_SEND_STATE_SEND_PN			(3)
#define DEVICE_INFO_SEND_STATE_RECV_PN			(4)
#define DEVICE_INFO_SEND_STATE_SEND_SN			(5)
#define DEVICE_INFO_SEND_STATE_RECV_SN			(6)
#define DEVICE_INFO_SEND_STATE_SEND_ROM_VER		(7)
#define DEVICE_INFO_SEND_STATE_RECV_ROM_VER		(8)
#define DEVICE_INFO_SEND_STATE_COM_CLOSE		(9)
#define DEVICE_INFO_SEND_STATE_END				(10)

/*------------------------- Server Macro Definition -------------------------*/
#define DEVICE_STATE_LOCAL_TEST					(0)
#define AI_SERVER_TICKET_TEST					(0)
#define AI_SERVER_TICKET_TEST_ARRAY_NUMBER		(256)
#define AI_SERVER_TICKET_TEST_POSITION_LENGTH	(64)

#define AI_SERVER_LANGUAGE_ENGLISH				(0)
#define AI_SERVER_LANGUAGE_HANWEN				(1)
#define AI_SERVER_LANGUAGE_CHINESE				(2)
#define AI_SERVER_LANGUAGE						(AI_SERVER_LANGUAGE_ENGLISH)
#if (AI_SERVER_LANGUAGE == AI_SERVER_LANGUAGE_ENGLISH)
#define MSG_WARING_INFORMATION					("Warning!")
#define MSG_SUCCESS_INFOMATION					("Information！")
#define MSG_LOGO_FINISH_CONVERT					("Finished!")
#define MSG_FILE_SELECT_LOCAL					("Please select local files!")
#define MSG_FILE_SELECT_REMOTE					("Please select device file!")
#define MSG_FILE_OPEN_ERROR						("Fail to open file!")
#define MSG_FILE_READ_ERROR						("Fail to read file!")
#define AI_SERVER_UI_INFO_INFORMATION			("Info")
#define AI_SERVER_UI_INFO_STATE					("State")
#define AI_SERVER_UI_INFO_CLOSE					("OFF")
#define AI_SERVER_UI_INFO_BANDRATE				(", bandrate:  ")
#define AI_SERVER_UI_INFO_PARITY				(", Parity:  ")
#define AI_SERVER_UI_INFO_DATA_BIT				(", Data:  ")
#define AI_SERVER_UI_INFO_STOP_BIT				(", Stop:  ")
#define AI_SERVER_UI_INFO_NORMAL				("Normal")
#define AI_SERVER_UI_INFO_UNNORMAL				("Error")
#define AI_SERVER_UI_INFO_COM_OPEN_OK			("Com Open...OK.")
#define AI_SERVER_UI_INFO_COM_OPER_ERROR		("Com Open Error！")
#define AI_SERVER_UI_INFO_COM_CLOSE_OK			("Com Close...OK.")
#define AI_SERVER_UI_INFO_COM_SEND_DATA			("Send Data...")
#define AI_SERVER_UI_INFO_COM_SEND_SATA_ERROR	("Send Data Error...")
#define AI_SERVER_UI_INFO_COM_RECV_DATA_TIMEOUT	("Recv Data...Timeout.")
#define AI_SERVER_UI_INFO_COM_RECV_DATA_ERROR	("Recv Data...Data Error.")
#define AI_SERVER_UI_INFO_COM_RECV_DATA_OK		("Recv Data...OK.")
#define AI_SERVER_UI_INFO_NET_YOLOV3			("Yolov3")
#define AI_SERVER_UI_INFO_IDENT					("Ident")
#define AI_SERVER_UI_INFO_STATE_COMMAND			("Command")
#define AI_SERVER_UI_INFO_STATE_CLOCK			("Clock")
#define AI_SERVER_UI_INFO_STATE_F16				("Float16")
#define AI_SERVER_UI_INFO_STATE_F32				("Float32")
#define AI_SERVER_UI_INFO_WEIGHTS_F32			("Weights")
#endif
#if (AI_SERVER_LANGUAGE == AI_SERVER_LANGUAGE_CHINESE)
#define MSG_WARING_INFORMATION					("警告！")
#define MSG_SUCCESS_INFOMATION					("信息！")
#define MSG_LOGO_FINISH_CONVERT					("成功！")
#define MSG_FILE_SELECT_SOURCE					("请选择本地文件！")
#define MSG_FILE_SELECT_REMOTE					("请选择设备文件！")
#define MSG_FILE_OPEN_ERROR						("打开文件错误！")
#define MSG_FILE_READ_ERROR						("读文件错误！")
#define AI_SERVER_UI_INFO_INFORMATION			("信息")
#define AI_SERVER_UI_INFO_CLOSE					("关闭")
#define AI_SERVER_UI_INFO_MAIN_STATUS			("状态")
#define AI_SERVER_UI_INFO_BANDRATE				(", 波特率:  ")
#define AI_SERVER_UI_INFO_PARITY				(", 校验位:  ")
#define AI_SERVER_UI_INFO_DATA_BIT				(", 数据位:  ")
#define AI_SERVER_UI_INFO_STOP_BIT				(", 停止位:  ")
#define AI_SERVER_UI_INFO_NORMAL				("正常")
#define AI_SERVER_UI_INFO_UNNORMAL				("异常")
#define AI_SERVER_UI_INFO_COM_OPEN_OK			("通信口打开...OK.")
#define AI_SERVER_UI_INFO_COM_OPER_ERROR		("通信口操作失败！")
#define AI_SERVER_UI_INFO_COM_CLOSE_OK			("通信口关闭...OK.")
#define AI_SERVER_UI_INFO_COM_SEND_DATA			("发送数据失败...")
#define AI_SERVER_UI_INFO_COM_SEND_SATA_ERROR	("发送数据失败...")
#define AI_SERVER_UI_INFO_COM_RECV_DATA_TIMEOUT	("获取数据...超时错误.")
#define AI_SERVER_UI_INFO_COM_RECV_DATA_ERROR	("获取数据...处理错误.")
#define AI_SERVER_UI_INFO_COM_RECV_DATA_OK		("获取数据...OK.")
#define AI_SERVER_UI_INFO_MAIN_FP16				("FP16")
#endif
/* comment */
#define AI_SERVER_SOFT_STATUS_STRING_LENGTH			(240)
/* unit */
#define AI_SERVER_DATA_UNIT_BASE_SW_N                  (2)
#define AI_SERVER_DATA_UNIT_BASE_HW_N                  (2)
#define AI_SERVER_DATA_UNIT_NETWORK_SW_N               (2)
#define AI_SERVER_DATA_UNIT_NETWORK_HW_N               (2)
#define AI_SERVER_DATA_UNIT_CONTROL_SW_N               (2)
#define AI_SERVER_DATA_UNIT_CONTROL_HW_N               (2)
#define AI_SERVER_DATA_UNIT_CENTER_SW_N                (2)
#define AI_SERVER_DATA_UNIT_CENTER_HW_N                (2)
#define AI_SERVER_DATA_UNIT_MANAGE_SW_N                (2)
#define AI_SERVER_DATA_UNIT_MANAGE_HW_N                (2)
#define AI_SERVER_DATA_UNIT_SERVER_SW_N                (2)
#define AI_SERVER_DATA_UNIT_SERVER_HW_N                (2)
#define AI_SERVER_DATA_UNIT_INDEX_INVALID              (0xFFFFFFFF)
/* ai server lnet */
#define AI_SERVER_LNET_TIMER										(1)
#define AI_SERVER_LNET_TIMER_PERIOD									(100)
/* ai server ident */
#define AI_SERVER_IDENT_TIMER										(1)
#define AI_SERVER_IDENT_TIMER_PERIOD								(1000)
/* server state perriod */
#define AI_SERVER_STATE_GENERAL_TIMER_PERIOD						(10000)
/* ai server state base */
#define AI_SERVER_STATE_BASE_TIMER									(1)
#define AI_SERVER_STATE_BASE_TIMER_PERIOD							(AI_SERVER_STATE_GENERAL_TIMER_PERIOD)
/* ai server state center soc */
#define AI_SERVER_STATE_CENTER_SOC_TIMER							(14)
#define AI_SERVER_STATE_CENTER_SOC_TIMER_PERIOD					(AI_SERVER_STATE_GENERAL_TIMER_PERIOD)
/* ai server state manage state */
#define AI_SERVER_STATE_CENTER_STATE_TIMER							(15)
#define AI_SERVER_STATE_CENTER_STATE_TIMER_PERIOD					(AI_SERVER_STATE_GENERAL_TIMER_PERIOD)
/* ai server state center device */
#define AI_SERVER_STATE_CENTER_DEVICE_TIMER						(16)
#define AI_SERVER_STATE_CENTER_DEVICE_TIMER_PERIOD					(AI_SERVER_STATE_GENERAL_TIMER_PERIOD)
/* ai server state base info */
#define AI_SERVER_STATE_BASE_INFO_TIMER							(17)
#define AI_SERVER_STATE_BASE_INFO_TIMER_PERIOD						(AI_SERVER_STATE_GENERAL_TIMER_PERIOD)
/* ai server state base state */
#define AI_SERVER_STATE_BASE_STATE_TIMER							(18)
#define AI_SERVER_STATE_BASE_STATE_TIMER_PERIOD					(AI_SERVER_STATE_GENERAL_TIMER_PERIOD)
/* ai server state base internal temp */
#define AI_SERVER_STATE_BASE_INTERNAL_TEMP_TIMER					(19)
#define AI_SERVER_STATE_BASE_INTERNAL_TEMP_TIMER_PERIOD			(AI_SERVER_STATE_GENERAL_TIMER_PERIOD)
#define AI_SERVER_STATE_BASE_INTERNAL_TEMP_MAX						(14000)
/* ai server state manage state */
#define AI_SERVER_STATE_MANAGE_STATE_TIMER							(20)
#define AI_SERVER_STATE_MANAGE_STATE_TIMER_PERIOD					(AI_SERVER_STATE_GENERAL_TIMER_PERIOD)
/* ai server state manage Network */
#define AI_SERVER_STATE_MANAGE_NETWORK_TIMER						(21)
#define AI_SERVER_STATE_MANAGE_NETWORK_TIMER_PERIOD				(AI_SERVER_STATE_GENERAL_TIMER_PERIOD)
/* ai server state manage general policy */
#define AI_SERVER_STATE_MANAGE_GENERAL_TIMER						(22)
#define AI_SERVER_STATE_MANAGE_GENERAL_TIMER_PERIOD				(AI_SERVER_STATE_GENERAL_TIMER_PERIOD)
#define AI_SERVER_STATE_MANAGE_GENERAL_ITEM_N						(17)
#define AI_SERVER_STATE_MANAGE_GENERAL_POS_LEFT					(0)
#define AI_SERVER_STATE_MANAGE_GENERAL_POS_HEIGHT					(13)
#define AI_SERVER_STATE_MANAGE_GENERAL_POS_WIDTH					(62)
#define AI_SERVER_STATE_MANAGE_GENERAL_POS_COLUMNS					(1)

/* server timeout */
#define AI_SERVER_DATA_RECEIVE_TIMEOUT					(2000)
#define AI_SERVER_DATA_RECEIVE_RTC_SET_TIMEOUT			(5000)
#define AI_SERVER_DATA_RETRY_TIMES						(5)
/* dialog state position */
#define AI_SERVER_STATE_DATA_POS_LEFT					(2)
#define AI_SERVER_STATE_DATA_POS_HEIGHT				(14)
#define AI_SERVER_STATE_DATA_POS_WIDTH					(220)
#define AI_SERVER_STATE_DATA_POS_COLUMNS				(4)
#define AI_SERVER_STATE_DATA_POS_BASE_INFO_WIDTH		(256)
#define AI_SERVER_STATE_DATA_POS_BASE_INFO_COLUMNS		(2)
#define AI_SERVER_STATE_DATA_POS_BASE_INFO_HEIGHT		(15)
#define AI_SERVER_STATE_DATA_POS_NETWORK_INFO_WIDTH	(180)
#define AI_SERVER_STATE_DATA_POS_NETWORK_INFO_COLUMNS	(3)
#define AI_SERVER_STATE_DATA_POS_CENTER_INFO_WIDTH		(180)
#define AI_SERVER_STATE_DATA_POS_CENTER_INFO_COLUMNS	(3)
#define AI_SERVER_STATE_DATA_POS_DEVICE_BASE_LEFT		(AI_SERVER_STATE_DATA_POS_LEFT+48)
#define AI_SERVER_STATE_DATA_POS_DEVICE_NETWORK_LEFT	(AI_SERVER_STATE_DATA_POS_DEVICE_BASE_LEFT+80)
#define AI_SERVER_STATE_DATA_POS_DEVICE_CONTROL_LEFT	(AI_SERVER_STATE_DATA_POS_DEVICE_NETWORK_LEFT+80)
#define AI_SERVER_STATE_DATA_POS_DEVICE_CENTER_LEFT	(AI_SERVER_STATE_DATA_POS_DEVICE_CONTROL_LEFT+80)
#define AI_SERVER_STATE_DATA_POS_DEVICE_MANAGE_LEFT	(AI_SERVER_STATE_DATA_POS_DEVICE_CENTER_LEFT+80)
#define AI_SERVER_STATE_DATA_POS_DEVICE_SERVER_LEFT	(AI_SERVER_STATE_DATA_POS_DEVICE_MANAGE_LEFT+80)
/* dialog config position */
#define AI_SERVER_CONFIG_DATA_POS_LEFT					(2)
#define AI_SERVER_CONFIG_DATA_POS_HEIGHT				(28)
#define AI_SERVER_CONFIG_DATA_POS_WIDTH					(185)
#define AI_SERVER_CONFIG_DATA_POS_COLUMNS				(4)
#define AI_SERVER_CONFIG_DATA_POS_BASE_INFO_WIDTH		(512)
#define AI_SERVER_CONFIG_DATA_POS_BASE_INFO_COLUMNS		(2)
/* config combo data */
#define AI_SERVER_CONFIG_DATA_COMBO_MAX					(16)
/* ai server config combo data */
#define AI_SERVER_CONFIG_NAME_DATA_COMBO_TIMER			(23)
#define AI_SERVER_CONFIG_NAME_DATA_COMBO_TIMER_PERIOD	(1000)
/* ai server state file content */
#define AI_SERVER_STATE_FILE_CONTENT_TIMER				(24)
#define AI_SERVER_STATE_FILE_CONTENT_TIMER_PERIOD		(1000)
/* ai server config combo data */
#define AI_SERVER_CONFIG_NAME_DATA_TIMER				(24)
#define AI_SERVER_CONFIG_NAME_DATA_TIMER_PERIOD			(1000)
/* ai server config button data */
#define AI_SERVER_CONFIG_BUTTON_TIMER					(25)
#define AI_SERVER_CONFIG_BUTTON_TIMER_PERIOD			(1000)
/* ai server config center state */
#define AI_SERVER_CONFIG_CENTER_STATE_TIMER				(1)
#define AI_SERVER_CONFIG_CENTER_STATE_TIMER_PERIOD			(1000)
/* ai server config center Network */
#define AI_SERVER_CONFIG_CENTER_NETWORK_TIMER				(1)
#define AI_SERVER_CONFIG_CENTER_NETWORK_TIMER_PERIOD		(1000)
/* ai server config manage state */
#define AI_SERVER_CONFIG_MANAGE_STATE_TIMER				(1)
#define AI_SERVER_CONFIG_MANAGE_STATE_TIMER_PERIOD			(1000)
/* ai server config manage Network */
#define AI_SERVER_CONFIG_MANAGE_NETWORK_TIMER				(1)
#define AI_SERVER_CONFIG_MANAGE_NETWORK_TIMER_PERIOD		(1000)
/* ai server config manage general policy */
#define AI_SERVER_CONFIG_MANAGE_GENERAL_TIMER				(1)
#define AI_SERVER_CONFIG_MANAGE_GENERAL_TIMER_PERIOD		(1000)
#define AI_SERVER_CONFIG_MANAGE_GENERAL_COMBO_N			(4)
#define AI_SERVER_CONFIG_MANAGE_GENERAL_NUMBER_N			(7)
/* ai server service check number */
#define AI_SERVER_SERVICE_CHECK_NUMBER						(100)
/* ai server update boot */
#define AI_SERVER_UPDATE_DEVICE_OPER_READ_BUFFER_LENGTH_MAX	(512)
#define AI_SERVER_UPDATE_DEVICE_OPER_WRITE_BUFFER_LENGTH_MAX	(512)
#define AI_SERVER_UPDATE_SERIAL_PACKET_LENGTH_MAX				(2048)
#define AI_SERVER_UPDATE_WRITE_IMAGE_CONTENT_PAGE_LENGTH		(64)
#define AI_SERVER_UPDATE_WRITE_IMAGE_CONTENT_LENGTH_MIN		(1)
#define AI_SERVER_UPDATE_WRITE_IMAGE_CONTENT_LENGTH_MAX		(1*1024)
#define AI_SERVER_UPDATE_WRITE_IMAGE_CONTENT_RETRY_TIMES		(3)
/* ai server update process bar */
#define AI_SERVER_UPDATE_WRITE_IMAGE_TIMER_PROCRSS_BAR			(1)
#define AI_SERVER_UPDATE_WRITE_IMAGE_TIMER_PROCESS_BAR_TIME	(1000)
#define AI_SERVER_UPDATE_BOOT_WRITE_IMAGE_TIMER				(2)
#define AI_SERVER_UPDATE_BOOT_WRITE_IMAGE_TIMER_PERIOD			(1000)
#define AI_SERVER_UPDATE_BOOT_WRITE_IMAGE_RETRY_TIMES			(3)
/* ai server update base info */
#define AI_SERVER_UPDATE_BOOT_INFO_TIMER						(1)
#define AI_SERVER_UPDATE_BOOT_INFO_TIMER_PERIOD				(1000)
/* ai server update base oper */
#define AI_SERVER_UPDATE_BOOT_OPER_TIMER						(1)
#define AI_SERVER_UPDATE_BOOT_OPER_TIMER_PERIOD				(1000)
/* ai server soc base */
#define AI_SERVER_SOC_TIMER									(1)
#define AI_SERVER_SOC_TIMER_PERIOD								(10000)
/* ai server soc info base */
#define AI_SERVER_SOC_INFO_TIMER								(1)
#define AI_SERVER_SOC_INFO_TIMER_PERIOD						(10000)
#define AI_SERVER_SOC_INFO_POS_LEFT							(2)
#define AI_SERVER_SOC_INFO_POS_HEIGHT							(14)
#define AI_SERVER_SOC_INFO_POS_WIDTH							(200)
#define AI_SERVER_SOC_INFO_POS_COLUMNS							(9)
/* ai server update process bar */
#define AI_SERVER_MANUFACTURE_BIN_TIMER_PROCRSS_BAR			(1)
#define AI_SERVER_MANUFACTURE_BIN_TIMER_PROCESS_BAR_TIME		(1000)
#define AI_SERVER_MANUFACTURE_BIN_TIMER						(2)
#define AI_SERVER_MANUFACTURE_BIN_TIMER_PERIOD					(1000)
#define AI_SERVER_MANUFACTURE_BIN_RETRY_TIMES					(3)
#define AI_SERVER_MANUFACTURE_BIN_CONTENT_LENGTH_MIN			(1)
#define AI_SERVER_MANUFACTURE_BIN_CONTENT_CONTENT_LENGTH_MAX	(256*1024)

/*------------------------- Type Definition----------------------------------*/

/*------------------------- Function Definition -----------------------------*/

#ifdef __cplusplus
}
#endif

#endif
/*------------------------- End ---------------------------------------------*/

