//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 SiAi.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_AI_SERVER_HELP_DIALOG       100
#define IDS_ABOUTBOX                    101
#define IDD_AI_SERVER_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDB_BACKGROUND                  139
#define IDB_BITMAP_LOGO                 141
#define IDD_AI_SERVER_DEVICE_STATE_NUMBER_DATA_PROCESS_BAR_DIALOG 150
#define IDD_AI_SERVER_DEVICE_UPDATE_BOOT_DIALOG 167
#define IDD_AI_SERVER_DEVICE_STATE_NUMBER_DATA_SWITCH_BAR_DIALOG 168
#define IDD_AI_SERVER_DEVICE_STATE_NAME_DATA_SWITCH_BAR_DIALOG 173
#define IDD_AI_SERVER_DEVICE_STATE_NAME_DATA_DIALOG 176
#define IDD_AI_SERVER_DEVICE_CONFIG_NUMBER_DATA_SWITCH_BAR_DIALOG 177
#define IDD_AI_SERVER_DEVICE_CONFIG_NUMBER_DATA_PROCESS_BAR_DIALOG 178
#define IDD_AI_SERVER_DEVICE_CONFIG_NUMBER_DATA_DIALOG 179
#define IDD_AI_SERVER_DEVICE_CONFIG_NAME_DATA_SWITCH_BAR_DIALOG 180
#define IDD_AI_SERVER_DEVICE_CONFIG_NAME_DATA_DIALOG 181
#define IDD_AI_SERVER_DEVICE_CONFIG_NAME_DATA_COMBO_DIALOG 210
#define IDD_AI_SERVER_DEVICE_CONFIG_BUTTON_DIALOG 212
#define IDD_AI_SERVER_DEVICE_CONFIG_NAME_DATA_COMBO_SHORT_DIALOG 217
#define IDD_AI_SERVER_DEVICE_CONFIG_NAME_DATA_SHORT_DIALOG 218
#define IDD_AI_SERVER_CONFIG_IDENT_DIALOG1 229
#define IDD_AI_SERVER_CONFIG_IDENT_DIALOG 229
#define IDD_AI_SERVER_STATE_FILE_CONTENT_DIALOG 230
#define IDD_AI_SERVER_STATE_FILE_CONTENT_F16_DIALOG 231
#define IDD_AI_SERVER_STATE_FILE_CONTENT_F32_DIALOG 232
#define IDD_AI_SERVER_STATE_NET_DIALOG  233
#define IDD_AI_SERVER_STATE_WEIGHTS_CONVERT_DIALOG 234
#define IDD_AI_SERVER_CONFIG_WEIGHTS_CONVERT_DIALOG 234
#define IDC_STATIC_SOFT_INFO            1000
#define IDC_AI_SERVER_TAB               1001
#define IDC_STATIC_SOFT_DESC            1003
#define IDC_STATIC_COM_SELECT           1004
#define IDC_STATIC_COM_CONFIG           1005
#define IDC_COMBO_COM_SELECT            1006
#define IDC_STATIC_SOFT_CLOSE           1007
#define IDC_BUTTON_SOFT_ABOUT           1008
#define IDC_BUTTON_SOFT_QUIT            1009
#define IDC_BUTTON_COM_RESET            1010
#define IDC_COMBO_COM_BAUDRATE          1011
#define IDC_STATIC_DEVICE_CONFIG        1012
#define IDC_STATIC_DEVICE_SELECT        1013
#define IDC_COMBO_DEVICE_SELECT         1014
#define IDC_BUTTON_DEVICE_RESET         1015
#define IDC_BUTTON_LOGO                 1421
#define IDC_STATIC_STATE_NUMBER_DATA    1442
#define IDC_STATIC_SWITCH_OFF           1443
#define IDC_STATIC_APP_DESCRIPTION      1444
#define IDC_STATIC_SWITCH_ON            1444
#define IDC_STATIC_COM_BAUDRATE         1445
#define IDC_STATIC_STATE_NAME_DATA      1445
#define IDC_STATIC_GROUP_SOFT_INFO      1446
#define IDC_NUMBER_DATA_PROGRESS        1461
#define IDC_SLIDER_NUMBER_DATA_SWITCH   1467
#define IDC_STATIC_STATE_NAME           1476
#define IDC_EDIT_CONFIG_NAME_DATA       1477
#define IDC_STATIC_CONFIG_NAME          1478
#define IDC_STATIC_CONFIG_NAME_DATA_UNIT 1479
#define IDC_BUTTON_CONFIG_SET           1480
#define IDC_COMBO_CONFIG_NAME_DATA      1482
#define IDC_BUTTON_CONFIG_CONFIRM       1487
#define IDC_STATIC_DATETIME             1490
#define IDC_BUTTON_FP16_TEST            1642
#define IDC_BUTTON_IDENT                1642
#define IDC_BUTTON_IDENT_FILE_BROWSER   1643
#define IDC_LIST_FP16_TEST              1645
#define IDC_LIST_IDENT                  1645
#define IDC_BUTTON_REFRESH              1647
#define IDC_BUTTON_PAGE_FIRST           1648
#define IDC_BUTTON_PAGE_NEXT            1649
#define IDC_BUTTON_PAGE_BEFORE          1650
#define IDC_BUTTON_PAGE_END             1651
#define IDC_BUTTON_REFRESH2             1652
#define IDC_BUTTON_DEBUG_STEP           1652
#define IDC_BUTTON_ACCURACY             1652
#define IDC_EDIT1                       1654
#define IDC_EDIT_FILE_PAGE_CONTENT      1654
#define IDC_EDIT_IDENT_FILE_PATH        1654
#define IDC_SCROLLBAR1                  1655
#define IDC_EDIT_F16_FILE_PATH          1655
#define IDC_STATIC_FILE                 1656
#define IDC_STATIC_SOURCE_IMAGE         1657
#define IDC_STATIC_SOURCE_IMAGE2        1658
#define IDC_STATIC_DESTINAION_IMAGE     1658
#define IDC_BUTTON_F16_FILE_BROWSER     1658
#define IDC_EDIT_F32_FILE_PATH          1659
#define IDC_BUTTON_F32_FILE_BROWSER     1660
#define IDC_AI_SERVER_NET_TAB           1661
#define IDC_BUTTON_CONVERT              1662

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1663
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
